---
name: tflint
on:
  push:
    branches:
      - main
      - master
      - prod
      - develop

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install prerequisites
        run: ./bin/install-ubuntu.sh
      - name: Terraform init
        run: terraform init --backend=false
      - name: tflint
        uses: reviewdog/action-tflint@54a5e5aed57dcfbb4662ec548de876df33d6288d # v1.25.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter
          level: error
